baseurl = "https://stepback.fumikiri.net"
enablerobotstxt = true
timezone = "America/New_York"
titlecasestyle = "Go"

[languages.en]
copyright = "Made with <a style=\"text-decoration: none;\" href=\"https://github.com/willfaught/paige/\">Paige</a>"
languagecode = "en-us"
languagedirection = "ltr"
languagename = "English"
title = "Stepping Back"
weight = 10

[languages.en.params.paige.site]
description = "A collection of illogical thoughts on railroad"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false
style = "github"

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["html", "paige-search"]
section = ["html"]
taxonomy = ["html"]
term = ["html"]

[pagination]
pagersize = 50

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 30

[[menu.main]]
identifier = "credits"
name = "Credits"
url = "/credits/"
weight = 40

[params.paige]
style = """
#paige-page-content,
#paige-page-pages > * {
  margin-left: auto;
  margin-right: auto;
  max-width: 40rem;
}
"""

[params.paige.pages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true
disable_word_count = true

[paige.pages.base_schema]
isAccessibleForFree = true
isFamilyFriendly = true

[params.paige.site]
disable_breadcrumbs = true
disable_credit = true

[params.paige.subpages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true


[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

# [[cascade]]
# [cascade._target]
# path = "{/authors,/authors/**}"
# [cascade.build]
# render = "never"

